main: com.perceivedev.chatmention.ChatMention
name: ChatMention
version: 1.0
description: A plugin to highlight name mentions
author: [Rayzr,I Al Istannen]
depend: [PerceiveCore]
commands:
  chatmention:
    description: "Reloads ChatMention"
    usage: "/<command> reload"
    permission: "ChatMention.reload"